<<<<<<< HEAD
services:
  app:
    image: node:24
    working_dir: /app
=======
services: 
  app:
    image: node:24
    working_dir: /app 
>>>>>>> 96405027ce6bb94297d90737b16e1f67dff8e2ed
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
      - "4173:4173"
    tty: true
    stdin_open: true